batch_size: 10
dirpath: models
enable_wandb: false
entity: test
gpus: 1
knowledge_data_path: datasets/gsm8k_/deepseek/gsm8k_pool_20.json
lr: 0.01
max_epochs: 10
model_checkpoint: models/model20221028-144859_6.pt
model_name: deepseek
num_sanity_val_steps: 0
num_workers: 0
pge_avg_samples: 5
project_name: test
run_name: test
sample_size: 8
save_top_k: 3
seed: 1
task: gsm8k
train_data_path: datasets/gsm8k_/gsm8k_train_100.json
val_check_interval: 1.0
valid_data_path: datasets/gsm8k_/gsm8k_val_100.json
